-- SET GLOBAL validate_password_policy=LOW;

SET PASSWORD = PASSWORD('MYSQL_ROOT_PSW');
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'MYSQL_ROOT_PSW' WITH GRANT OPTION;
FLUSH privileges;

CREATE USER 'appUser'@'%' IDENTIFIED BY 'MYSQL_APPUSER_PSW';
FLUSH privileges;

CREATE DATABASE `app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, EXECUTE, INDEX, INSERT, REFERENCES, SELECT, SHOW VIEW, TRIGGER, UPDATE ON app.* TO 'appUser'@'%';

FLUSH PRIVILEGES;